site_name: SRS — Агрегатор доставки продуктов
site_description: Software Requirements Specification — агрегатор доставки продуктов
site_author: iGoods Team
repo_url: https://github.com/bestdeejay-design/srs-docs
repo_name: bestdeejay-design/srs-docs

theme:
  name: material
  language: ru
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Тёмная тема
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Светлая тема
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.suggest
    - content.code.copy

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/bestdeejay-design/docs
  generator: false

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true
      toc_depth: 4
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

plugins:
  - search

nav:
  - Главная: index.md
  - Том 1: tom-1.md
  - Том 2: tom-2.md
